name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # або 'master' якщо твоя головна гілка так називається

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --token "$FIREBASE_TOKEN"
